### ISSUE TITLE
Are you planning to switch from MooTools to jQuery?

### ISSUE THREAD

**Issue by philip-sorokin** [compojoom/lib_compojoom#2]
Hello. Since MooTools library is deprecated in Joomla, I would like to ask you if you are planning to switch from MooTools to jQuery in future releases of Compojoom?

Thank you for your answer!

**Comment by yvesh** [comment]
Hello, yes 99% are already jQuery.. We don't use Mootools any longer, only some old remains are still left.. (Not for long)

**Comment by philip-sorokin** [comment]
Does this mean that if I renew a subscription, I can download a new version of CComment that does not use Mootools?

**Comment by compojoom** [comment]
CComment doesn't yet have a non-Mootools version, but we will provide one.
